services:
  mongobackend:
    image: mongo:latest
    restart: unless-stopped  
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongodb-alfabyte 

  backend:
    container_name: backend-alfabyte
    restart: unless-stopped  
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongobackend
    environment:
      - APP_PORT=3000
      - MONGO_ATLAS=mongodb+srv://anthonyarango01:12345@databasesx.silq0.mongodb.net/
      - DB_NAME=databasesx
      - MONGO_ATLAS_DB_USER=anthonyarango01
      - MONGO_ATLAS_DB_PASSWORD=12345
      - JWT_SECRET=Secret_Key
    volumes:
      - ./:/app
      - /app/node_modules


volumes:
  mongo-data: